baseURL: "https://alanliang.com/"
languageCode: zh-TW
title: Alan's blog
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Alan's blog
  description: "some drafts and notes"
  keywords: [Blog, tech, PaperMod]
  author: Alan Liang
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: true
  showtoc: false
  tocopen: false

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  homeInfoParams:
    Title: "Alan's blog 🐔"
    Content: some drafts and notes
  
